// O'zbekiston ma'muriy-hududiy bo'linishi:
// 12 viloyat + Qoraqalpog'iston Respublikasi + Toshkent shahri = 14 hudud
// Har bir hudud ichida tumanlar (va shaharlar) ro'yxati: [uz, ru]

export type RegionData = {
  name: string;
  nameRu: string;
  order: number;
  districts: [uz: string, ru: string][];
};

export const regions: RegionData[] = [
  {
    name: "Toshkent shahri",
    nameRu: "город Ташкент",
    order: 1,
    districts: [
      ["Bektemir", "Бектемир"],
      ["Chilonzor", "Чиланзар"],
      ["Mirobod", "Мирабад"],
      ["Mirzo Ulug'bek", "Мирзо-Улугбек"],
      ["Olmazor", "Алмазар"],
      ["Sergeli", "Сергели"],
      ["Uchtepa", "Учтепа"],
      ["Shayxontohur", "Шайхантахур"],
      ["Yakkasaroy", "Яккасарай"],
      ["Yashnobod", "Яшнабад"],
      ["Yunusobod", "Юнусабад"],
      ["Yangihayot", "Янгихаёт"],
    ],
  },
  {
    name: "Toshkent viloyati",
    nameRu: "Ташкентская область",
    order: 2,
    districts: [
      ["Bekobod", "Бекабад"],
      ["Bo'ka", "Бука"],
      ["Bo'stonliq", "Бостанлык"],
      ["Chinoz", "Чиназ"],
      ["Qibray", "Кибрай"],
      ["Ohangaron", "Ахангаран"],
      ["Oqqo'rg'on", "Аккурган"],
      ["Parkent", "Паркент"],
      ["Piskent", "Пскент"],
      ["Quyichirchiq", "Куйичирчик"],
      ["O'rtachirchiq", "Уртачирчик"],
      ["Yangiyo'l", "Янгиюль"],
      ["Yuqorichirchiq", "Юкоричирчик"],
      ["Zangiota", "Зангиата"],
      ["Bo'stonliq (Chirchiq)", "Чирчик"],
      ["Olmaliq shahri", "город Алмалык"],
      ["Angren shahri", "город Ангрен"],
      ["Nurafshon shahri", "город Нурафшан"],
    ],
  },
  {
    name: "Andijon viloyati",
    nameRu: "Андижанская область",
    order: 3,
    districts: [
      ["Andijon", "Андижанский"],
      ["Asaka", "Асака"],
      ["Baliqchi", "Балыкчи"],
      ["Bo'z", "Боз"],
      ["Buloqboshi", "Булакбаши"],
      ["Izboskan", "Избаскан"],
      ["Jalaquduq", "Джалакудук"],
      ["Xo'jaobod", "Ходжаабад"],
      ["Qo'rg'ontepa", "Кургантепа"],
      ["Marhamat", "Мархамат"],
      ["Oltinko'l", "Алтынкуль"],
      ["Paxtaobod", "Пахтаабад"],
      ["Shahrixon", "Шахрихан"],
      ["Ulug'nor", "Улугнор"],
      ["Andijon shahri", "город Андижан"],
      ["Xonobod shahri", "город Ханабад"],
    ],
  },
  {
    name: "Buxoro viloyati",
    nameRu: "Бухарская область",
    order: 4,
    districts: [
      ["Buxoro", "Бухарский"],
      ["G'ijduvon", "Гиждуван"],
      ["Jondor", "Джандар"],
      ["Kogon", "Каган"],
      ["Olot", "Алат"],
      ["Peshku", "Пешку"],
      ["Qorako'l", "Каракуль"],
      ["Qorovulbozor", "Караулбазар"],
      ["Romitan", "Ромитан"],
      ["Shofirkon", "Шафиркан"],
      ["Vobkent", "Вабкент"],
      ["Buxoro shahri", "город Бухара"],
      ["Kogon shahri", "город Каган"],
    ],
  },
  {
    name: "Farg'ona viloyati",
    nameRu: "Ферганская область",
    order: 5,
    districts: [
      ["Bag'dod", "Багдад"],
      ["Beshariq", "Бешарык"],
      ["Buvayda", "Бувайда"],
      ["Dang'ara", "Дангара"],
      ["Farg'ona", "Ферганский"],
      ["Furqat", "Фуркат"],
      ["Qo'shtepa", "Куштепа"],
      ["Quva", "Кува"],
      ["Rishton", "Риштан"],
      ["So'x", "Сох"],
      ["Toshloq", "Ташлак"],
      ["Uchko'prik", "Учкуприк"],
      ["O'zbekiston", "Узбекистанский"],
      ["Yozyovon", "Язъяван"],
      ["Oltiariq", "Алтыарык"],
      ["Farg'ona shahri", "город Фергана"],
      ["Marg'ilon shahri", "город Маргилан"],
      ["Quvasoy shahri", "город Кувасай"],
      ["Qo'qon shahri", "город Коканд"],
    ],
  },
  {
    name: "Jizzax viloyati",
    nameRu: "Джизакская область",
    order: 6,
    districts: [
      ["Arnasoy", "Арнасай"],
      ["Baxmal", "Бахмаль"],
      ["Do'stlik", "Дустлик"],
      ["Forish", "Фариш"],
      ["G'allaorol", "Галляарал"],
      ["Sharof Rashidov", "Шараф Рашидовский"],
      ["Mirzacho'l", "Мирзачуль"],
      ["Paxtakor", "Пахтакор"],
      ["Yangiobod", "Янгиабад"],
      ["Zafarobod", "Зафарабад"],
      ["Zarbdor", "Зарбдар"],
      ["Zomin", "Зааминский"],
      ["Jizzax shahri", "город Джизак"],
    ],
  },
  {
    name: "Qashqadaryo viloyati",
    nameRu: "Кашкадарьинская область",
    order: 7,
    districts: [
      ["Chiroqchi", "Чиракчи"],
      ["Dehqonobod", "Дехканабад"],
      ["G'uzor", "Гузар"],
      ["Qamashi", "Камаши"],
      ["Qarshi", "Каршинский"],
      ["Kasbi", "Касби"],
      ["Kitob", "Китаб"],
      ["Koson", "Касан"],
      ["Mirishkor", "Миришкор"],
      ["Muborak", "Мубарек"],
      ["Nishon", "Нишан"],
      ["Shahrisabz", "Шахрисабзский"],
      ["Yakkabog'", "Яккабаг"],
      ["Ko'kdala", "Кокдала"],
      ["Qarshi shahri", "город Карши"],
      ["Shahrisabz shahri", "город Шахрисабз"],
    ],
  },
  {
    name: "Navoiy viloyati",
    nameRu: "Навоийская область",
    order: 8,
    districts: [
      ["Konimex", "Канимех"],
      ["Karmana", "Кармана"],
      ["Qiziltepa", "Кызылтепа"],
      ["Xatirchi", "Хатырчи"],
      ["Navbahor", "Навбахор"],
      ["Nurota", "Нурата"],
      ["Tomdi", "Тамдынский"],
      ["Uchquduq", "Учкудук"],
      ["Navoiy shahri", "город Навои"],
      ["Zarafshon shahri", "город Зарафшан"],
    ],
  },
  {
    name: "Namangan viloyati",
    nameRu: "Наманганская область",
    order: 9,
    districts: [
      ["Chortoq", "Чартак"],
      ["Chust", "Чуст"],
      ["Kosonsoy", "Касансай"],
      ["Mingbuloq", "Мингбулак"],
      ["Namangan", "Наманганский"],
      ["Norin", "Нарын"],
      ["Pop", "Пап"],
      ["To'raqo'rg'on", "Туракурган"],
      ["Uchqo'rg'on", "Учкурган"],
      ["Uychi", "Уйчи"],
      ["Yangiqo'rg'on", "Янгикурган"],
      ["Davlatobod", "Давлатабад"],
      ["Namangan shahri", "город Наманган"],
    ],
  },
  {
    name: "Samarqand viloyati",
    nameRu: "Самаркандская область",
    order: 10,
    districts: [
      ["Bulung'ur", "Булунгур"],
      ["Ishtixon", "Иштыхан"],
      ["Jomboy", "Джамбай"],
      ["Kattaqo'rg'on", "Каттакурган"],
      ["Qo'shrabot", "Кошрабад"],
      ["Narpay", "Нарпай"],
      ["Nurobod", "Нурабад"],
      ["Oqdaryo", "Акдарья"],
      ["Pastdarg'om", "Пастдаргом"],
      ["Paxtachi", "Пахтачи"],
      ["Payariq", "Пайарык"],
      ["Samarqand", "Самаркандский"],
      ["Toyloq", "Тайлак"],
      ["Urgut", "Ургут"],
      ["Samarqand shahri", "город Самарканд"],
      ["Kattaqo'rg'on shahri", "город Каттакурган"],
    ],
  },
  {
    name: "Sirdaryo viloyati",
    nameRu: "Сырдарьинская область",
    order: 11,
    districts: [
      ["Boyovut", "Баяут"],
      ["Guliston", "Гулистанский"],
      ["Mirzaobod", "Мирзаабад"],
      ["Oqoltin", "Акалтын"],
      ["Sayxunobod", "Сайхунабад"],
      ["Sardoba", "Сардоба"],
      ["Sirdaryo", "Сырдарьинский"],
      ["Xovos", "Хаваст"],
      ["Guliston shahri", "город Гулистан"],
      ["Shirin shahri", "город Ширин"],
      ["Yangiyer shahri", "город Янгиер"],
    ],
  },
  {
    name: "Surxondaryo viloyati",
    nameRu: "Сурхандарьинская область",
    order: 12,
    districts: [
      ["Angor", "Ангор"],
      ["Bandixon", "Бандихан"],
      ["Boysun", "Байсун"],
      ["Denov", "Денау"],
      ["Jarqo'rg'on", "Джаркурган"],
      ["Qiziriq", "Кизирик"],
      ["Qumqo'rg'on", "Кумкурган"],
      ["Muzrabot", "Музрабат"],
      ["Oltinsoy", "Алтынсай"],
      ["Sariosiyo", "Сариасия"],
      ["Sherobod", "Шерабад"],
      ["Sho'rchi", "Шурчи"],
      ["Termiz", "Термезский"],
      ["Uzun", "Узун"],
      ["Termiz shahri", "город Термез"],
    ],
  },
  {
    name: "Xorazm viloyati",
    nameRu: "Хорезмская область",
    order: 13,
    districts: [
      ["Bog'ot", "Багат"],
      ["Gurlan", "Гурлен"],
      ["Xonqa", "Ханка"],
      ["Hazorasp", "Хазарасп"],
      ["Xiva", "Хивинский"],
      ["Qo'shko'pir", "Кошкупыр"],
      ["Shovot", "Шават"],
      ["Urganch", "Ургенчский"],
      ["Yangiariq", "Янгиарык"],
      ["Yangibozor", "Янгибазар"],
      ["Tuproqqal'a", "Тупраккала"],
      ["Urganch shahri", "город Ургенч"],
      ["Xiva shahri", "город Хива"],
    ],
  },
  {
    name: "Qoraqalpog'iston Respublikasi",
    nameRu: "Республика Каракалпакстан",
    order: 14,
    districts: [
      ["Amudaryo", "Амударьинский"],
      ["Beruniy", "Берунийский"],
      ["Chimboy", "Чимбайский"],
      ["Ellikqal'a", "Элликкалинский"],
      ["Kegeyli", "Кегейлийский"],
      ["Mo'ynoq", "Муйнакский"],
      ["Nukus tumani", "Нукусский"],
      ["Qanliko'l", "Канлыкульский"],
      ["Qo'ng'irot", "Кунградский"],
      ["Qorao'zak", "Караузякский"],
      ["Shumanay", "Шуманайский"],
      ["Taxtako'pir", "Тахтакупырский"],
      ["To'rtko'l", "Турткульский"],
      ["Xo'jayli", "Ходжейлийский"],
      ["Bo'zatov", "Бозатауский"],
      ["Nukus shahri", "город Нукус"],
    ],
  },
];

// Hudud markazlari taxminiy koordinatalari (xaritada nuqta uchun fallback)
export const regionCoords: Record<string, [number, number]> = {
  "Toshkent shahri": [41.3111, 69.2797],
  "Toshkent viloyati": [41.0, 69.3],
  "Andijon viloyati": [40.7821, 72.3442],
  "Buxoro viloyati": [39.7681, 64.4556],
  "Farg'ona viloyati": [40.3864, 71.7864],
  "Jizzax viloyati": [40.1158, 67.8422],
  "Qashqadaryo viloyati": [38.8616, 65.789],
  "Navoiy viloyati": [40.0844, 65.3792],
  "Namangan viloyati": [40.9983, 71.6726],
  "Samarqand viloyati": [39.627, 66.975],
  "Sirdaryo viloyati": [40.4897, 68.7842],
  "Surxondaryo viloyati": [37.2242, 67.2783],
  "Xorazm viloyati": [41.55, 60.6333],
  "Qoraqalpog'iston Respublikasi": [42.4731, 59.6103],
};
